language: python

python:
    - 2.7

env:
    - TOX_ENV=py26
    - TOX_ENV=py27
    - TOX_ENV=pypy
    - TOX_ENV=py26-twtrunk
    - TOX_ENV=py27-twtrunk
    - TOX_ENV=pypy-twtrunk
    - TOX_ENV=py26-tw132
    - TOX_ENV=py27-tw132
    - TOX_ENV=pypy-tw132
    - TOX_ENV=py26-tw131
    - TOX_ENV=py27-tw131
    - TOX_ENV=pypy-tw131

install:
    - pip install -q tox requests==2.1.0

script: tox -e $TOX_ENV

notifications:
  email: false

