language: python

python:
    - 2.7

env:
    - TOX_ENV=py26
    - TOX_ENV=py27
    - TOX_ENV=pypy
    - TOX_ENV=py26-twtrunk
    - TOX_ENV=py27-twtrunk
    - TOX_ENV=pypy-twtrunk
    - TOX_ENV=py26-tw132
    - TOX_ENV=py27-tw132
    - TOX_ENV=pypy-tw132
    - TOX_ENV=py26-tw131
    - TOX_ENV=py27-tw131
    - TOX_ENV=pypy-tw131
    - TOX_ENV=py26-tw130
    - TOX_ENV=py27-tw130
    - TOX_ENV=pypy-tw130


install:
    - ./.travis/install.sh

script: tox -e $TOX_ENV

notifications:
  email: false

